# Generated by Django 4.1.1 on 2022-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionusuario',
            name='avatar',
            field=models.ImageField(blank=True, height_field=50, null=True, upload_to='avatares', width_field=50),
        ),
    ]
