# Generated by Django 4.1.1 on 2022-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_extensionusuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
