# Generated by Django 4.1.1 on 2022-10-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0002_auto_alter_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
