# Generated by Django 4.1.1 on 2022-11-12 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avanzado', '0004_vehiculo_avatar_vehiculo_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
